### PR TITLE
Typo fix

### LINKED ISSUE #5: PnP First Time Contributor Session Scheduling - November
Hello, future PnP Contributors! 😉

All those referenced below should be receiving an email today with instructions and a link to select one of two scheduled "PnP First Time Contributor" November sessions. Please let me know if you do not receive it.

Please be sure to check your spam or junk boxes just in case it gets flagged as such.

Thanks again for your collaborative community spirit!! 👍

David

@arjunumenon,@LouFarho,@TheAndrewHess,@arnostac,@josephjtsoleraincdev,@rahulsuryawanshi,@westerdaled,@bricenocar,@amit12joshi,@troystaylor,@billbrockbank,@datocrats-org,@ValerasNarbutas,@CindyRay,@ashiqf,@McDKirra,@mikezimm,@kiransripada,@WeeTeck

### PR DESCRIPTION
**Pull request by ValerasNarbutas**
p to P - typo fix

#### Category
- [x] Content fix
- [ ] New article

#### Related issues:
- fixes #5 

#### What's in this Pull Request?

Practice session for contribution to PnP
issue #5

### CODE REVIEW

**Comment by ValerasNarbutas** [comment]
Hey @PopWarner , 
can you merge it? :)
hugs and kisses :)

**Comment by PopWarner** [comment]
@ValerasNarbutas Thank you...can you create a new PR without the issue reference. 👍

**Comment by ValerasNarbutas** [comment]
sure, here you go @PopWarner

**Comment by ValerasNarbutas** [comment]
#19  is ready for you @PopWarner

**Pull request closed without merging**
