### PR TITLE
SharePoint is spelled with an uppercase "P"!

### PR DESCRIPTION
**Pull request by hugoabernier**
#### Category
- [x] Content fix
- [ ] New article

#### What's in this Pull Request?

David Warner II made me do this!

### CODE REVIEW

**Comment by hugoabernier** [comment]
@PopWarner  this is a very cool exercise! Thanks for setting this up

**Comment by ValerasNarbutas** [comment]
cool, thanks @PopWarner  and @hugoabernier

**Comment by arnostac** [comment]
👍

**Comment by PopWarner** [comment]
@hugoabernier Good work!!!

**Pull request merged**
